# Generated by Django 2.0.9 on 2018-12-24 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demo_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=30, verbose_name='Author')),
                ('Title', models.CharField(max_length=200)),
                ('Condition', models.CharField(choices=[('cond_one', 'Good!'), ('cond_two', 'Not bad'), ('cond_three', 'Very bad')], default='cond_one', max_length=20)),
                ('Weapon', models.CharField(choices=[('sec_one', 'Bomb'), ('sec_two', 'Rifle'), ('sec_three', 'No one')], default='sec_three', max_length=20)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_slug', models.SlugField(default='golosuvalka')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('policy', models.TextField()),
                ('party', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
