<<<<<<< HEAD
# Generated by Django 2.0.9 on 2018-12-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 2.0.9 on 2018-12-18 14:07

from django.db import migrations, models
>>>>>>> 8dcc7132c6e00f58472e89fd5d470258e1ac61b6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 8dcc7132c6e00f58472e89fd5d470258e1ac61b6
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='demo_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_slug', models.SlugField(default='golosuvalka')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('policy', models.TextField()),
                ('party', models.CharField(blank=True, max_length=200, null=True)),
>>>>>>> 8dcc7132c6e00f58472e89fd5d470258e1ac61b6
            ],
        ),
    ]
