# Generated by Django 2.0.9 on 2019-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
