# Generated by Django 2.0.9 on 2018-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo_model',
            name='Condition',
            field=models.CharField(choices=[('Good!', 'good'), ('Not bad', 'so so'), ('Very bad', 'bad')], default='Good!', max_length=20),
        ),
    ]
