# Generated by Django 2.0.9 on 2018-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_demo_model_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo_model',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='demo_model',
            name='created_date',
        ),
        migrations.AddField(
            model_name='demo_model',
            name='Author',
            field=models.CharField(default='Author', max_length=30),
        ),
        migrations.AddField(
            model_name='demo_model',
            name='Weapon',
            field=models.CharField(choices=[('sec_one', 'Bomb'), ('sec_two', 'Rifle'), ('sec_three', 'No one')], default='sec_three', max_length=20),
        ),
        migrations.AlterField(
            model_name='demo_model',
            name='Condition',
            field=models.CharField(choices=[('cond_one', 'Good!'), ('cond_two', 'Not bad'), ('cond_three', 'Very bad')], default='cond_one', max_length=20),
        ),
    ]
