# Generated by Django 2.0.9 on 2019-01-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_userattempt_userattemptquestionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattemptquestionanswer',
            old_name='qestion_answer',
            new_name='question_answer',
        ),
    ]
